name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push to Docker Hub
        uses: eviive/actions/docker-hub-build-push@main
        with:
          docker-hub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
          docker-hub-repository: portfolio
          lfs: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            cd /opt/${{ secrets.VPS_HOST }}
            docker compose pull portfolio
            docker compose up -d --no-deps portfolio
            docker image prune -f
